[metadata]
name = pyerskafka
version = attr: pyerskafka.__version__
url = https://github.com/pawelplesniak/pyerskafka
long_description = file: docs/README.md
long_description_content_type = text/markdown

[options]
packages = find_namespace:
package_dir = =src
# include_package_data = true
python_requires = >= 3.6
# Dependencies are in setup.py for GitHub's dependency graph.

[options.packages.find]
where = src
include_package_data = true

[options.entry_points]
console_scripts = 
    pyerskafka_print_test = pyerskafka.apps.__main_first_test__:main